# 从错误或错误断言获取基础类型

> 原文：<https://golangbyexample.com/error-claiming-golang/>

# **概述**

有两种获取基础类型的方法

*   使用。({type})断言

如果断言成功，那么它将返回相应的错误，否则它将恐慌。下面是语法

```go
err := err.({type})
```

最好使用`ok`变量来防止断言失败时的恐慌。下面是它的语法。如果错误基础类型正确，`ok`变量将被设置为 true

```go
err, ok := err.({type})
```

使用**的**作为**功能出错**包-[`golang.org/pkg/errors/`](https://golang.org/pkg/errors/)。使用**作为**功能优于使用。({type})断言，因为它通过顺序展开第一个错误来检查匹配，并在展开的每一步将其与目标错误进行匹配。下面是 is 函数的语法

```go
func As(err error, target interface{}) bool
```

`As`函数会在第一个参数中找到可以匹配目标的第一个错误。一旦找到匹配项，它会将目标设置为该错误值。

# **代码**

让我们看一个例子

```go
package main

import (
	"errors"
	"fmt"
	"os"
)

func main() {

	err := openFile("non-existing.txt")

	if e, ok := err.(*os.PathError); ok {
		fmt.Printf("Using Assert: Error e is of type path error. Path: %v\n", e.Path)
	} else {
		fmt.Println("Using Assert: Error not of type path error")
	}

	var pathError *os.PathError
	if errors.As(err, &pathError) {
		fmt.Printf("Using As function: Error e is of type path error. Path: %v\n", pathError.Path)
	}
}

func openFile(fileName string) error {
	_, err := os.Open("non-existing.txt")
	if err != nil {
		return err
	}
	return nil
}
```

**输出**：

```go
Using Assert: Error e is of type path error. Path: non-existing.txt
Using As function: Error e is of type path error. Path: non-existing.txt
```

在上面的程序中，我们有一个函数 openFile，我们试图打开一个不存在的类型，因此它会引发一个错误。那么我们用两种方式来断言错误

*   使用。断言运算符。如果错误基础类型为 ***os，ok 变量将设置为 true。路径错误**否则将设置为假

```go
e,ok := err.(*os.PathError); ok
```

*   使用错误包的**作为**功能

```go
errors.As(err, &pathError)
```

这两种方法都正确地断言错误属于类型 ***os。路径错误**作为由**打开文件**功能返回的错误，类型为 ***os。路径错误**

上面我们提到使用**作为**函数比使用。({type})断言，因为它通过顺序展开第一个错误来检查匹配，并在展开的每一步将其与目标错误匹配。让我们看一个例子来理解这一点

```go
import (
	"errors"
	"fmt"
	"os"
)

func main() {
	var pathError *os.PathError
	err := openFile("non-existing.txt")

	if e, ok := err.(*os.PathError); ok {
		fmt.Printf("Using Assert: Error e is of type path error. Error: %v\n", e)
	} else {
		fmt.Println("Using Assert: Error not of type path error")
	}

	if errors.As(err, &pathError) {
		fmt.Printf("Using As function: Error e is of type path error. Error: %v\n", pathError)
	}
}

func openFile(fileName string) error {
	_, err := os.Open("non-existing.txt")
	if err != nil {
		return fmt.Errorf("Error opening: %w", err)
	}
	return nil
}
```

**输出**：

```go
Using Assert: Error not of type path error
Using As function: Error e is of type path error. Error: open non-existing.txt: no such file or directory
```

上面的程序和前面的程序几乎一样，不同的是在 openFile 函数中我们也包装了错误

```go
return fmt.Errorf("Error opening: %w", err)
```

*   那个。断言输出

```go
Using Assert: Error not of type path error
```

*   而作为功能输出

```go
Using As function: Error e is of type path error. Error: open non-existing.txt: no such file or directory
```

这是因为`openFile`函数返回的错误包装了 ***os。路径错误**未被点('.'捕捉到的错误)断言但被**捕获为**函数