# 如何创建恐慌

> 原文：<https://golangbyexample.com/how-create-panic-golang/>

# **概述**

恐慌类似于 golang 的异常。恐慌是指在异常情况下退出程序。程序中出现恐慌有两种方式

*   程序中的运行时错误

*   通过显式调用紧急函数。当程序无法继续并且必须退出时，程序员可以调用这个函数

Go 提供了一个特殊的功能来创建恐慌。下面是函数的语法

```go
func panic(v interface{})
```

程序员可以显式调用这个函数来创建恐慌。它以一个空接口作为参数。当程序中出现恐慌时，它会输出两件事

*   作为参数传递给紧急函数的错误消息

*   恐慌发生的栈跟踪

# **运行时错误恐慌**

程序中的运行时错误可能在以下情况下发生

*   越界数组访问
*   在零指针上调用函数
*   在封闭信道上发送
*   不正确的类型断言

让我们看一个由越界数组访问引起的运行时错误的例子。

```go
package main

import "fmt"

func main() {

	a := []string{"a", "b"}
	print(a, 2)
}

func print(a []string, index int) {
	fmt.Println(a[index])
}
```

**输出**

```go
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
main.checkAndPrint(...)
        main.go:12
main.main()
        /main.go:8 +0x1b
exit status 2
```

在上面的程序中，我们有一个长度为 2 的切片，我们试图在**打印**功能中访问索引为 3 的切片。不允许越界访问，从输出中可以看出，这将造成恐慌。请注意，在输出中有两件事

*   错误消息
*   恐慌发生的栈跟踪

在很多情况下，程序中可能会发生运行时错误。我们不会提到所有这些，但你会明白的

# **明确调用恐慌功能**

程序员可以显式调用紧急函数的一些情况是:

*   该函数需要一个有效的参数，但是提供了一个零参数。在这种情况下，程序不能继续，它会引起一个通过零参数的恐慌

*   程序无法继续的任何其他情况。

我们来看一个例子。

```go
package main

import "fmt"

func main() {

	a := []string{"a", "b"}
	checkAndPrint(a, 2)
}

func checkAndPrint(a []string, index int) {
	if index > (len(a) - 1) {
		panic("Out of bound access for slice")
	}
	fmt.Println(a[index])
}
```

**输出**

```go
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
main.checkAndPrint(0xc00009af58, 0x2, 0x2, 0x2)
        main.go:15 +0x31
main.main()
        main.go:8 +0x7d
exit status 2
```

在上面的程序中，我们再次有一个函数 `checkAndPrint` ，它接受一个切片作为参数和一个索引。然后检查传递的索引是否大于切片长度减 1。如果是，那么它超出了切片的访问范围，因此它会恐慌。如果不是，则打印该索引处的值。再次注意，在输出中有两件事

*   错误消息

*   恐慌发生的栈跟踪